[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "yetayaltizale-database"
db_connection = "AIRFLOW_CONN_AWS_RDS_POSTGRES"
username = 'postgres'  # Your RDS username
password = 'Yetayalmaster2024'  # Your new RDS password
host = 'yetayaltizale-database.cvwhaidrmrqj.us-east-2.rds.amazonaws.com'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'postgres'  # Using the default database name
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "de300spring2024-airflow"
s3_file_key = "wine.csv"

[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "quality"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95

[student]
student_name = "yetayaltizale"
assignment = "pro-de-pipeline"